// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeShot
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeShot.06cf14ac-c16c-4c61-9e83-2edd8692648c";
        public const string Name = "CodeShot";
        public const string Description = @"Turn the current editor selection into a polished PNG screenshot without leaving Visual Studio. Copy it to the clipboard or save it to disk.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "screenshot, image, png, code, snippet, capture, share, tool window";
        public const bool IsPreview = false;
    }
}
