// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeShot
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodeShotString = "a7a7b4b8-f629-4a80-9156-c3dcaae4256a";
        public static Guid CodeShot = new Guid(CodeShotString);
        public const string CodeShotToolWindowString = "ce9b4700-7154-4196-9957-858230f19734";
        public static Guid CodeShotToolWindow = new Guid(CodeShotToolWindowString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ShowCodeShotWindowCommand = 0x0100;
        public const int CodeShotToolbar = 0x1000;
        public const int ToolbarActionsGroup = 0x1010;
        public const int ToolbarFontGroup = 0x1020;
        public const int ToolbarOptionsGroup = 0x1030;
        public const int OptionsMenu = 0x1040;
        public const int OptionsMenuGroup = 0x1050;
        public const int OptionsMenuSettingsGroup = 0x1060;
        public const int OptionsMenuLineNumbersGroup = 0x1070;
        public const int ToolbarAnnotationGroup = 0x1080;
        public const int AnnotationMenuToolsGroup = 0x1090;
        public const int AnnotationMenuActionsGroup = 0x10A0;
        public const int AnnotationMenu = 0x10B0;
        public const int RefreshPreviewCommand = 0x0110;
        public const int CopyImageCommand = 0x0120;
        public const int SaveImageCommand = 0x0130;
        public const int ShowLineNumbersCommand = 0x0140;
        public const int ShowTitleBarCommand = 0x0150;
        public const int UseRealLineNumbersCommand = 0x0190;
        public const int KeepIndentationCommand = 0x01A0;
        public const int ClearHighlightsCommand = 0x01B0;
        public const int SelectAnnotationCommand = 0x01C0;
        public const int RectangleAnnotationCommand = 0x01D0;
        public const int RedactAnnotationCommand = 0x01E0;
        public const int EraserAnnotationCommand = 0x01F0;
        public const int ClearAnnotationsCommand = 0x0200;
        public const int ArrowAnnotationCommand = 0x0210;
        public const int HighlightAnnotationCommand = 0x0220;
        public const int TextAnnotationCommand = 0x0230;
        public const int UndoAnnotationCommand = 0x0240;
        public const int RedoAnnotationCommand = 0x0250;
        public const int OpenOptionsCommand = 0x0180;
        public const int FontFamilyCombo = 0x0160;
        public const int FontFamilyComboList = 0x0161;
        public const int FontSizeCombo = 0x0170;
        public const int FontSizeComboList = 0x0171;
    }
}
